---
title: "Nonparametric Analysis of UK Road Accidents"
subtitle: "GAM on accident severities"
author:
    - "Valeria Iapaolo"
    - "Oswaldo Morales"
    - "Riccardo Morandi"
    - "Abylai Orynbassar"
output:
    html_document:
        toc: true
        toc_float: true
        number_sections: true
    pdf_document:
        toc: true
        toc_depth: 3
        number_section: true
date: "2023-11-10"
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    #dev = c('pdf'),
    fig.align = 'center',
    #fig.path = 'output/',
    fig.height = 6,
    fig.width = 12
)
```

```{r libraries inclusions, include=FALSE}
library(mgcv) #to use GAM
library(tidyverse)
library(mgcViz)
```

```{r}
load("../../clean data/full_collisions.RData")

df_18 <- full_collisions %>% filter(accident_year == 2018)
rm(full_collisions)

glimpse(df_18)
```

```{r, echo = FALSE}
# #plot of the covariates I'm using
# df_18 %>% ggplot(aes(as.factor(speed_limit))) + geom_bar(aes(fill = accident_severity))
# df_18 %>% ggplot(aes(time,color = accident_severity)) + geom_freqpoly(bins = 48)
# df_18 %>% ggplot(aes(x = number_of_vehicles, fill = accident_severity)) + 
#   geom_bar(position = "fill") + xlim(c(1,10))
# 
# df_18 %>% ggplot(aes(x = number_of_casualties, fill = accident_severity)) + 
#   geom_bar(position = "fill") + xlim(c(1,10))

```

```{r}
dat <- 
  df_18 %>% select(accident_severity, 
                   speed_limit, time, number_of_vehicles, number_of_casualties,
                   longitude,latitude) %>%
  mutate(accident_severity = case_when(
      accident_severity == "Fatal" ~ 1,
      accident_severity == "Serious" ~ 1,
      accident_severity == "Slight" ~ 0
    )
  )

dat$time <- as.numeric(dat$time)


dat
```


```{r}
R = 3# the number of categories
b <- gam(accident_severity ~ 
           number_of_vehicles +
           s(speed_limit, bs='cr', k = 3) +
           s(time, bs = "cc"),
         family=binomial(), data = dat)

#OBS: bam same as gam, but faster for large data

#com: the number if unique values in speed_limit is low, so we need to specify k
```


```{r}
summary(b)
```

```{r}
b
```

```{r}
plot(b,pages=1)

```


```{r}
gam.check(b)

```


```{r}
b$family$getTheta(TRUE)
```


## Adding spatial gp


```{r}
dat <- 
  df_18 %>% select(accident_severity, 
                   speed_limit, time, number_of_vehicles, number_of_casualties,
                   longitude,latitude) %>%
  mutate(accident_severity = case_when(
      accident_severity == "Fatal" ~ 1,
      accident_severity == "Serious" ~ 1,
      accident_severity == "Slight" ~ 0
    )
  )

dat$time <- as.numeric(dat$time)


# preprocessing spatial
geom_map <- map_data("world",region = "UK") %>% filter(!(subregion %in% c("Northern Ireland")))
geom_map_no_islands <- geom_map %>% filter(group == 15)


max_lat <- range(geom_map_no_islands$lat)
max_lon <- range(geom_map_no_islands$long)


#for plot
geom_map_red <- geom_map %>% filter(lat <= max_lat[2] & lat >= max_lat[1] &
                                       long <= max_lon[2] & long >= max_lon[1])

# avoiding the extremes:
dat <- dat %>% filter(latitude <= max_lat[2] & latitude >= max_lat[1] &
                                       longitude <= max_lon[2] & longitude >= max_lon[1])



# df_binned <- df_spatial %>% mutate(latitude = ceiling(10*latitude)/10,longitude = ceiling(10*longitude)/10) %>% group_by(latitude,longitude,date) %>% summarise(n = n()) %>% ungroup()
dat

```






```{r}
R = 3# the number of categories
b <- gam(accident_severity ~ 
           number_of_vehicles +
           s(speed_limit, bs='cr', k = 3) +
           s(time, bs = "cc") +
           s(longitude,latitude,bs = "gp",k = 100,m = c(1,0.5)),
         family=binomial(), data = dat)

#OBS: bam same as gam, but faster for large data

#com: the number if unique values in speed_limit is low, so we need to specify k
```


```{r}
summary(b)
```

```{r}
b
```

```{r}
plot(b)

```


```{r}
gam.check(b)

```


```{r}
b$family$getTheta(TRUE)
```




# previous covariates:

```{r}
load("../../clean data/full_collisions.RData")


full_collisions <- full_collisions %>% filter(accident_year %in% c(2018))

glimpse(full_collisions)
```

```{r}
dat <- 
  full_collisions %>% filter(!(light_conditions %in% c("Data missing or out of range", "Darkness - lighting unknown"))) %>%
  # select(number_of_casualties,
  #                  accident_severity, speed_limit, time, number_of_vehicles) %>%
  mutate(number_of_casualties = number_of_casualties-1,
         
         accident_severity = case_when(
            accident_severity == "Fatal" ~ 1,
            accident_severity == "Serious" ~ 1,
            accident_severity == "Slight" ~ 0),
         
         weekend = ifelse(day_of_week %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), 0, 1),
         
         light_conditions = case_when(
            light_conditions == "Daylight" ~ "Daylight",
            light_conditions == "Darkness - lights lit"  ~ "Darkness - lights lit",
            light_conditions %in% c("Darkness - lights unlit", "Darkness - no lighting") ~ "Darkness - no lights"
            ),
         
         previous_accident = ifelse(carriageway_hazards == "Previous accident", 1, 0)
         
         
         )

dat$time <- as.numeric(dat$time)



# preprocessing spatial
geom_map <- map_data("world",region = "UK") %>% filter(!(subregion %in% c("Northern Ireland")))
geom_map_no_islands <- geom_map %>% filter(group == 15)


max_lat <- range(geom_map_no_islands$lat)
max_lon <- range(geom_map_no_islands$long)


#for plot
geom_map_red <- geom_map %>% filter(lat <= max_lat[2] & lat >= max_lat[1] &
                                       long <= max_lon[2] & long >= max_lon[1])

# avoiding the extremes:
dat <- dat %>% filter(latitude <= max_lat[2] & latitude >= max_lat[1] &
                                       longitude <= max_lon[2] & longitude >= max_lon[1])



# df_binned <- df_spatial %>% mutate(latitude = ceiling(10*latitude)/10,longitude = ceiling(10*longitude)/10) %>% group_by(latitude,longitude,date) %>% summarise(n = n()) %>% ungroup()
dat

```



```{r}
gam_ncas_binary_cov <- gam(accident_severity~
           number_of_casualties +
           # year +
           s(time, bs = "cc") +
           weekend +
           # date +
           s(number_of_vehicles, bs = "cr", k = 5) +
           # first_road_class +
           # second_road_class +
           # road_type +
           s(speed_limit, bs='cr', k = 5) +
           # junction_detail +
           # junction_control +
           # pedestrian_crossing_human_control +
           # pedestrian_crossing_physical_facilities +
           light_conditions,
           # weather_conditions +
           # special_conditions_at_site +
           # previous_accident, # carriageway_hazards +
             
           # did_police_officer_attend_scene_of_accident,
           # trunk_road_flag + ?

           # road_surface_conditions +
           # urban_or_rural_area,
           
           # s(longitude,latitude,bs = "gp",k = 100,m = c(1,0.5)),
         family= binomial(),
         data = dat)

```


```{r}
summary(gam_ncas_binary_cov)
```

```{r}
gam_ncas_binary_cov
```


```{r}
# plot(b, ylim = c(-0.3, 0.3))
plot(gam_ncas_binary_cov, select = 1, ylim = c(-0.3, 0.3), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
plot(gam_ncas_binary_cov, select = 2, xlim = c(0,15), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
plot(gam_ncas_binary_cov, select = 3, ylim = c(-0.3, 0.3), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
# plot(b,pages=3, ylim = c(-0.3, 0.3))

```



```{r}
gam.check(gam_ncas_binary_cov)

```



### +gp
```{r}
gam_ncas_binary_cov_gp <- gam(accident_severity ~
           number_of_casualties +
           # year +
           s(time, bs = "cc") +
           weekend +
           # date +
           s(number_of_vehicles, bs = "cr", k = 5) +
           # first_road_class +
           # second_road_class +
           # road_type +
           s(speed_limit, bs='cr', k = 5) +
           # junction_detail +
           # junction_control +
           # pedestrian_crossing_human_control +
           # pedestrian_crossing_physical_facilities +
           light_conditions+
           # weather_conditions +
           # special_conditions_at_site +
           # previous_accident, # carriageway_hazards +
             
           # did_police_officer_attend_scene_of_accident,
           # trunk_road_flag + ?

           # road_surface_conditions +
           # urban_or_rural_area,
           
           s(longitude,latitude,bs = "gp",k = 100,m = c(1,0.5)),
         family= binomial(),
         data = dat)

```


```{r}
summary(gam_ncas_binary_cov_gp)
```

```{r}
gam_ncas_binary_cov_gp
```

```{r}
# plot(b, ylim = c(-0.3, 0.3))
plot(gam_ncas_binary_cov_gp, select = 1, ylim = c(-0.3, 0.3), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
plot(gam_ncas_binary_cov_gp, select = 2, xlim = c(0,15), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
plot(gam_ncas_binary_cov_gp, select = 3, ylim = c(-0.3, 0.3), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
# plot(b,pages=3, ylim = c(-0.3, 0.3))

```

```{r}
plot(gam_ncas_binary_cov_gp, select = 4)

```


```{r}
gam.check(gam_ncas_binary_cov_gp)

```