---
title: "Nonparametric Analysis of UK Road Accidents"
subtitle: "Permutational ANOVA location"
author:
    - "Valeria Iapaolo"
    - "Oswaldo Morales"
    - "Riccardo Morandi"
    - "Abylai Orynbassar"
output:
    html_document:
        toc: true
        toc_float: true
        number_sections: true
    pdf_document:
        toc: true
        toc_depth: 3
        number_section: true
date: "2023-12-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    #dev = c('pdf'),
    fig.align = 'center'
    #fig.path = 'output/',
    #fig.height = 6,
    #fig.width = 12
)
```


```{r cars}
library(tidyverse)
library(mgcv)
library(splines)
library(lubridate)
library(ggplot2)
library(conformalInference)
library(knitr)
library(sp)
library(rgl)
library(splines)
library(pbapply)
library(devtools)
library(visreg)
library(mgcViz)
```



```{r pressure, echo=FALSE}
load("~/Documents/GitHub/NPS_RoadTrafficCollision/clean data/full_collisions.RData")
glimpse(full_collisions)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r}
set.seed(4244)
bin_size <- 0.01 

sampled_data_locations <- full_collisions
# binned longitude and latitude
sampled_data_locations <- sampled_data_locations %>%
  mutate(
    binned_longitude = floor(longitude / bin_size) * bin_size,
    binned_latitude = floor(latitude / bin_size) * bin_size
  )

location_crash_data <- sampled_data_locations %>%
  group_by(binned_longitude, binned_latitude) %>%
  summarise(number_of_crashes = n())
```

```{r}
anova_result <- aov(number_of_crashes ~ binned_longitude + binned_latitude+ binned_longitude:binned_latitude, data = location_crash_data)
summary(anova_result)
```
```{r}
T0_long_lat <- summary.aov(aov(number_of_crashes ~ binned_longitude + binned_latitude+ binned_longitude:binned_latitude,data = location_crash_data))[[1]][3,4]

T0_long_lat
```

```{r}
aov.H0long_lat <- aov(number_of_crashes ~ binned_longitude + binned_latitude, data = location_crash_data)
aov.H0long_lat

```
```{r}
n <- dim(location_crash_data)[1]
residuals.H0long_lat <- aov.H0long_lat$residuals

B = 1e3
pb = progress::progress_bar$new(total = B, format = " Processing [:bar] :percent eta: :eta")
T_long_lat <- numeric(B)
for(perm in 1:B){
  permutation <- sample(n)
  # permute the residuals
  residuals.H0long_lat <- residuals.H0long_lat[permutation]
  nmbcrash.perm.H0long_lat <- aov.H0long_lat$fitted + residuals.H0long_lat
  # re-fit full model to calculate statistic
  T_long_lat[perm] <- summary.aov(aov( nmbcrash.perm.H0long_lat ~ binned_longitude + binned_latitude + binned_longitude:binned_latitude, data = location_crash_data))[[1]][3,4]
  pb$tick()
}
```
```{r}
sum(T_long_lat >= T0_long_lat)/B
```
```{r}
hist(T_long_lat, xlim = range(0, ceiling(max(T_long_lat)+6)), breaks = 30)
abline(v=T0_long_lat,col=3,lwd=2)
```

```{r}
plot(ecdf(T_long_lat), xlim = range(0, ceiling(max(T_long_lat)+6)))
abline(v=T0_long_lat, col=3,lwd=4)
```


```{r}
ggplot()+aes(T_long_lat)+geom_histogram(binwidth = 0.4) + geom_vline(aes(xintercept=T0_long_lat), color= "red")
        

```
```{r}
ggplot()+aes(T_long_lat)+stat_ecdf(geom = "step") + geom_vline(aes(xintercept=20.546), color= "red")

```
```{r}
save(T_long_lat, file="interaction.Rdata")
```

