---
title: "Nonparametric Analysis of UK Road Accidents"
subtitle: "GAM on number of casualties"
author:
    - "Valeria Iapaolo"
    - "Oswaldo Morales"
    - "Riccardo Morandi"
    - "Abylai Orynbassar"
output:
    html_document:
        toc: true
        toc_float: true
        number_sections: true
    pdf_document:
        toc: true
        toc_depth: 3
        number_section: true
date: "2023-11-10"
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    #dev = c('pdf'),
    fig.align = 'center',
    #fig.path = 'output/',
    fig.height = 9,
    fig.width = 18
)
```

```{r libraries inclusions, include=FALSE}
library(mgcv) #to use GAM
library(tidyverse)
```

```{r}
load("../../clean data/full_collisions.RData")


full_collisions <- full_collisions %>% filter(accident_year %in% c(2018))

glimpse(full_collisions)
```

# Comments:

Looking the plots in EDA_collisions_nCasualties, we can observe that - the distribution looks like a poisson

-   spline wrt the time is a good idea
-   Linear wrt n vehicles
-   spline wrt speed limit
-   junction control ??
-   light_conditions ??

# Test Poisson

```{r}
vcd_res = vcd::goodfit(table(full_collisions$number_of_casualties - 1), type="poisson")
summary(vcd_res)
```

# GAM: poisson

```{r}
dat <- 
  full_collisions %>% 
  # select(number_of_casualties,
  #                  accident_severity, speed_limit, time, number_of_vehicles) %>%
  mutate(accident_severity = case_when(
         accident_severity == "Fatal" ~ 3,
         accident_severity == "Serious" ~ 2,
         accident_severity == "Slight" ~ 1)
         ) %>%
  mutate(number_of_casualties = number_of_casualties-1)

dat$time <- as.numeric(dat$time)
```

```{r}
# b <- gam(number_of_casualties ~
#            # accident_severity + 
#            number_of_vehicles +
#            s(speed_limit, bs='cr', k = 4) +
#            s(time, bs = "cc") +
#            urban_or_rural_area +
#            day_of_week,
#          family= poisson(),
#          data = dat)

## R-sq.(adj) =  -1.17   Deviance explained = 10.4%


#OBS: bam same as gam, but faster for large data

#com: the number if unique values in speed_limit is low, so we need to specify k



b <- gam(number_of_casualties ~
           accident_severity +
           s(time, bs = "cc") +
           day_of_week +
           
           number_of_vehicles +
           # first_road_class +
           # second_road_class + 
           road_type +
           s(speed_limit, bs='cr', k = 4) +
           junction_detail + 
           junction_control +
           pedestrian_crossing_human_control +
           pedestrian_crossing_physical_facilities +
           light_conditions +
           weather_conditions +
           special_conditions_at_site +
           carriageway_hazards +
           did_police_officer_attend_scene_of_accident +
           trunk_road_flag +
           
           # road_surface_conditions +
           urban_or_rural_area,
         family= poisson(),
         data = dat)

# R-sq.(adj) =  -0.66   Deviance explained = 12.3%
# UBRE = -0.059622  Scale est. = 1         n = 252617

```

```{r}
summary(b)
```

```{r}
b
```

```{r}
plot(b,pages=1)

```

```{r}
gam.check(b)

```

```{r}
b$family$getTheta(TRUE)
```

# GAM zero inflated poisson

```{r}
dat <- 
  full_collisions %>% filter(!(light_conditions %in% c("Data missing or out of range", "Darkness - lighting unknown"))) %>%
  # select(number_of_casualties,
  #                  accident_severity, speed_limit, time, number_of_vehicles) %>%
  mutate(number_of_casualties = number_of_casualties-1,
         
         accident_severity = case_when(
            accident_severity == "Fatal" ~ 3,
            accident_severity == "Serious" ~ 2,
            accident_severity == "Slight" ~ 1),
         
         weekend = ifelse(day_of_week %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), 0, 1),
         
         light_conditions = case_when(
            light_conditions == "Daylight" ~ "Daylight",
            light_conditions == "Darkness - lights lit"  ~ "Darkness - lights lit",
            light_conditions %in% c("Darkness - lights unlit", "Darkness - no lighting") ~ "Darkness - no lights"
            ),
         
         previous_accident = ifelse(carriageway_hazards == "Previous accident", 1, 0)
         
         
         )

dat$time <- as.numeric(dat$time)
```

```{r}
# b <- gam(number_of_casualties ~
#            # accident_severity +
#            number_of_vehicles +
#            s(speed_limit, bs='cr', k = 4) +
#            s(time, bs = "cc") +
#            urban_or_rural_area +
#            day_of_week,
#          family= ziP(),
#          data = dat)

b <- gam(number_of_casualties ~
           accident_severity +
           # year +
           s(time, bs = "cc") +
           weekend +
           # date +
           s(number_of_vehicles, bs = "cr", k = 5) +
           # first_road_class +
           # second_road_class +
           # road_type +
           s(speed_limit, bs='cr', k = 5) +
           # junction_detail +
           # junction_control +
           # pedestrian_crossing_human_control +
           # pedestrian_crossing_physical_facilities +
           light_conditions,
           # weather_conditions +
           # special_conditions_at_site +
           # previous_accident, # carriageway_hazards + ## previous accident has p-value 0.9301 
           # did_police_officer_attend_scene_of_accident,
           # trunk_road_flag + ?

           # road_surface_conditions +
           # urban_or_rural_area,
         family= ziP(),
         data = dat)


```

```{r}

# accident severity + weekend + light conditions + special conditions at site + previous accident + s(time, bs = "cc") + s(number of vehicles, bs = "cr", k = 3) + s(speed limit, bs='cr', k = 5)
```

```{r}
summary(b)
```

```{r}
b
```

```{r}
# plot(b, ylim = c(-0.3, 0.3))
plot(b, select = 1, ylim = c(-0.3, 0.3), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
plot(b, select = 2, xlim = c(0,15), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
plot(b, select = 3, ylim = c(-0.3, 0.3), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
# plot(b,pages=3, ylim = c(-0.3, 0.3))

```

```{r}
gam.check(b)

```

```{r}
b$family$getTheta(TRUE)
```

# GAM: quasipoisson

```{r}
dat <- 
  full_collisions %>% 
  # select(number_of_casualties,
  #                  accident_severity, speed_limit, time, number_of_vehicles) %>%
  mutate(accident_severity = case_when(
         accident_severity == "Fatal" ~ 3,
         accident_severity == "Serious" ~ 2,
         accident_severity == "Slight" ~ 1)
         ) %>%
  mutate(number_of_casualties = number_of_casualties - 1)

dat$time <- as.numeric(dat$time)
```

```{r}
b <- gam(number_of_casualties ~
           # accident_severity +
           number_of_vehicles +
           s(speed_limit, bs='cr', k = 4) +
           s(time, bs = "cc") +
           urban_or_rural_area +
           day_of_week,
         family= quasipoisson(),
         data = dat)

# b <- gam(number_of_casualties ~
#            accident_severity +
#            s(time, bs = "cc") +
#            day_of_week +
#            
#            number_of_vehicles +
#            # first_road_class +
#            # second_road_class + 
#            road_type +
#            s(speed_limit, bs='cr', k = 4) +
#            junction_detail + 
#            junction_control +
#            pedestrian_crossing_human_control +
#            pedestrian_crossing_physical_facilities +
#            light_conditions +
#            weather_conditions +
#            special_conditions_at_site +
#            carriageway_hazards +
#            did_police_officer_attend_scene_of_accident +
#            trunk_road_flag +
#            
#            # road_surface_conditions +
#            urban_or_rural_area,
#          family= poisson(),
#          data = dat)

# R-sq.(adj) =  -0.66   Deviance explained = 12.3%
# UBRE = -0.059622  Scale est. = 1         n = 252617

```

```{r}
summary(b)
```

```{r}
b
```

```{r}
plot(b,pages=1)

```

```{r}
gam.check(b)

```

```{r}
b$family$getTheta(TRUE)
```

# GAM negbin

```{r}
dat <- 
  full_collisions %>% 
  # select(number_of_casualties,
  #                  accident_severity, speed_limit, time, number_of_vehicles) %>%
  mutate(accident_severity = case_when(
         accident_severity == "Fatal" ~ 3,
         accident_severity == "Serious" ~ 2,
         accident_severity == "Slight" ~ 1)
         ) %>%
  mutate(number_of_casualties = number_of_casualties-1)

dat$time <- as.numeric(dat$time)
```

```{r}
b <- gam(number_of_casualties ~
           # accident_severity +
           number_of_vehicles +
           s(speed_limit, bs='cr', k = 4) +
           s(time, bs = "cc") +
           urban_or_rural_area +
           day_of_week,
         family= negbin(3),
         data = dat)

# b <- gam(number_of_casualties ~
#            accident_severity +
#            s(time, bs = "cc") +
#            day_of_week +
#            
#            number_of_vehicles +
#            # first_road_class +
#            # second_road_class + 
#            road_type +
#            s(speed_limit, bs='cr', k = 4) +
#            junction_detail + 
#            junction_control +
#            pedestrian_crossing_human_control +
#            pedestrian_crossing_physical_facilities +
#            light_conditions +
#            weather_conditions +
#            special_conditions_at_site +
#            carriageway_hazards +
#            did_police_officer_attend_scene_of_accident +
#            trunk_road_flag +
#            
#            # road_surface_conditions +
#            urban_or_rural_area,
#          family= poisson(),
#          data = dat)

# R-sq.(adj) =  -0.66   Deviance explained = 12.3%
# UBRE = -0.059622  Scale est. = 1         n = 252617

```

```{r}
summary(b)
```

```{r}
b
```

```{r}
plot(b,pages=1)

```

```{r}
gam.check(b)

```

```{r}
b$family$getTheta(TRUE)
```



# ziP with spatial gp


```{r}
dat <- 
  full_collisions %>% filter(!(light_conditions %in% c("Data missing or out of range", "Darkness - lighting unknown"))) %>%
  # select(number_of_casualties,
  #                  accident_severity, speed_limit, time, number_of_vehicles) %>%
  mutate(number_of_casualties = number_of_casualties-1,
         
         accident_severity = case_when(
            accident_severity == "Fatal" ~ 3,
            accident_severity == "Serious" ~ 2,
            accident_severity == "Slight" ~ 1),
         
         weekend = ifelse(day_of_week %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), 0, 1),
         
         light_conditions = case_when(
            light_conditions == "Daylight" ~ "Daylight",
            light_conditions == "Darkness - lights lit"  ~ "Darkness - lights lit",
            light_conditions %in% c("Darkness - lights unlit", "Darkness - no lighting") ~ "Darkness - no lights"
            ),
         
         previous_accident = ifelse(carriageway_hazards == "Previous accident", 1, 0)
         
         
         )

dat$time <- as.numeric(dat$time)



# preprocessing spatial
geom_map <- map_data("world",region = "UK") %>% filter(!(subregion %in% c("Northern Ireland")))
geom_map_no_islands <- geom_map %>% filter(group == 15)


max_lat <- range(geom_map_no_islands$lat)
max_lon <- range(geom_map_no_islands$long)


#for plot
geom_map_red <- geom_map %>% filter(lat <= max_lat[2] & lat >= max_lat[1] &
                                       long <= max_lon[2] & long >= max_lon[1])

# avoiding the extremes:
dat <- dat %>% filter(latitude <= max_lat[2] & latitude >= max_lat[1] &
                                       longitude <= max_lon[2] & longitude >= max_lon[1])



# df_binned <- df_spatial %>% mutate(latitude = ceiling(10*latitude)/10,longitude = ceiling(10*longitude)/10) %>% group_by(latitude,longitude,date) %>% summarise(n = n()) %>% ungroup()
dat

```



```{r}

b <- gam(number_of_casualties ~
           accident_severity +
           # year +
           s(time, bs = "cc") +
           weekend +
           # date +
           s(number_of_vehicles, bs = "cr", k = 5) +
           # first_road_class +
           # second_road_class +
           # road_type +
           s(speed_limit, bs='cr', k = 5) +
           # junction_detail +
           # junction_control +
           # pedestrian_crossing_human_control +
           # pedestrian_crossing_physical_facilities +
           light_conditions+
           # weather_conditions +
           # special_conditions_at_site +
           # previous_accident, # carriageway_hazards + ## previous accident has p-value 0.9301 
           # did_police_officer_attend_scene_of_accident,
           # trunk_road_flag + ?

           # road_surface_conditions +
           # urban_or_rural_area,
           s(longitude,latitude,bs = "gp",k = 100,m = c(1,0.5)),
         family= ziP(),
         data = dat)


```

```{r}

# accident severity + weekend + light conditions + special conditions at site + previous accident + s(time, bs = "cc") + s(number of vehicles, bs = "cr", k = 3) + s(speed limit, bs='cr', k = 5)
```

```{r}
summary(b)
```

```{r}
b
```

```{r}
# plot(b, ylim = c(-0.3, 0.3))
plot(b, select = 1, ylim = c(-0.3, 0.3), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
plot(b, select = 2, xlim = c(0,15), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
plot(b, select = 3, ylim = c(-0.3, 0.3), cex.axis=2, cex.lab = 1.5, n = 150, lwd = 2)
# plot(b,pages=3, ylim = c(-0.3, 0.3))

```

```{r}
plot(b, select = 4)
```



```{r}
gam.check(b)

```


