---
title: "Nonparametric Analysis of UK Road Accidents"
subtitle: "Permutational ANOVA Severity"
author:
    - "Valeria Iapaolo"
    - "Oswaldo Morales"
    - "Riccardo Morandi"
    - "Abylai Orynbassar"
output:
    html_document:
        toc: true
        toc_float: true
        number_sections: true
    pdf_document:
        toc: true
        toc_depth: 3
        number_section: true
date: "2023-12-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    #dev = c('pdf'),
    fig.align = 'center'
    #fig.path = 'output/',
    #fig.height = 6,
    #fig.width = 12
)
```


```{r cars}
library(tidyverse)
library(mgcv)
library(splines)
library(lubridate)
library(ggplot2)
library(conformalInference)
library(knitr)
library(sp)
library(rgl)
library(splines)
library(pbapply)
library(devtools)
library(visreg)
library(mgcViz)
```



```{r pressure, echo=FALSE}
load("~/Documents/GitHub/NPS_RoadTrafficCollision/clean data/full_casualties.RData")
glimpse(full_casualties)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r}
g <-  nlevels(full_casualties$casualty_class)
n <- dim(full_casualties)[1]

head(full_casualties$casualty_class)
head(full_casualties$casualty_severity)
table(full_casualties$casualty_class)
table(full_casualties$casualty_severity)
```

```{r}
full_casualties$casualty_severity <- factor(full_casualties$casualty_severity, levels = c("Fatal", "Serious", "Slight"), labels = c(1, 2, 3))
full_casualties$casualty_severity <- as.numeric(full_casualties$casualty_severity)


plot(full_casualties$casualty_class, full_casualties$casualty_severity, xlab='treat',col=rainbow(g),main='Original Data')

anova_result <- aov(casualty_severity ~ casualty_class, data = full_casualties)
summary(anova_result)

```


```{r}
B = 1e3
seed = 2044
T_stat <- numeric(B) 
n <- dim(full_casualties)[1]
pb = progress::progress_bar$new(total = B, format = " Processing [:bar] :percent eta: :eta")
for(perm in 1:B){
  # Permutation:
  permutation <- sample(1:n)
  casualty_severity_perm <- full_casualties$casualty_severity[permutation]
  casualty_class_perm <- aov( casualty_severity_perm~ full_casualties$casualty_class)
  
  # Test statistic:
  T_stat[perm] <- summary(casualty_class_perm)[[1]][1,4]
  pb$tick()
}
```
```{r}
save(T_stat, file="severity_perm.Rdata")
```


```{r}
T0 <- summary(anova_result)[[1]][1,4]  # extract the test statistic
T0
#quartz()
hist(T_stat, xlim = range(0,12), breaks = 40)
abline(v=11,col=3,lwd=2)
```
```{r}
p_val <- sum(T_stat>=T0)/B
p_val
```


```{r}
plot(ecdf(T_stat), xlim = c(-1, 12))
abline(v=T0, col=3,lwd=4)
```
```{r}
load("severity_perm.Rdata")
ggplot()+aes(T_stat)+geom_histogram(binwidth = 0.4) + geom_vline(aes(xintercept=11.0201), color= "red")

```

```{r}
ggplot()+aes(T_stat)+stat_ecdf(geom = "step") + geom_vline(aes(xintercept=11.0201), color= "red")

```
```{r}

```





Year 2018

```{r}
load("../../clean data/full_collisions.RData")
full_collisions_test <- full_collisions %>% filter(accident_year %in% c(2019))
full_collisions <- full_collisions %>% filter(accident_year %in% c(2018))

glimpse(full_collisions)
```

```{r}
dat <- 
  full_collisions %>% 
  filter(!(light_conditions %in% c("Data missing or out of range", "Darkness - lighting unknown"))) %>%
  # select(number_of_casualties,
  #                  accident_severity, speed_limit, time, number_of_vehicles) %>%
  mutate(number_of_casualties = number_of_casualties-1,
         
         accident_severity = case_when(
            accident_severity == "Fatal" ~ 3,
            accident_severity == "Serious" ~ 2,
            accident_severity == "Slight" ~ 1),
         
         weekend = ifelse(day_of_week %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), 0, 1),
         
         light_conditions = case_when(
            light_conditions == "Daylight" ~ "Daylight",
            light_conditions == "Darkness - lights lit"  ~ "Darkness - lights lit",
            light_conditions %in% c("Darkness - lights unlit", "Darkness - no lighting") ~ "Darkness - no lights"
            ),
         
         previous_accident = ifelse(carriageway_hazards == "Previous accident", 1, 0)
         
         
         )

dat$time <- as.numeric(dat$time)



# preprocessing spatial
geom_map <- map_data("world",region = "UK") %>% filter(!(subregion %in% c("Northern Ireland")))
geom_map_no_islands <- geom_map %>% filter(group == 15)


max_lat <- range(geom_map_no_islands$lat)
max_lon <- range(geom_map_no_islands$long)


#for plot
geom_map_red <- geom_map %>% filter(lat <= max_lat[2] & lat >= max_lat[1] &
                                       long <= max_lon[2] & long >= max_lon[1])

# avoiding the extremes:
dat <- dat %>% filter(latitude <= max_lat[2] & latitude >= max_lat[1] &
                                       longitude <= max_lon[2] & longitude >= max_lon[1])



# df_binned <- df_spatial %>% mutate(latitude = ceiling(10*latitude)/10,longitude = ceiling(10*longitude)/10) %>% group_by(latitude,longitude,date) %>% summarise(n = n()) %>% ungroup()
dat
```



Permutation test on year 2018
```{r}
g <-  nlevels(dat$number_of_casualties)
n <- dim(dat)[1]


anova_result <- aov(accident_severity ~ number_of_casualties + weekend + light_conditions, data = dat)
summary(anova_result)
```

```{r}
T0_nmb_casualties <-summary(anova_result) [[1]][1,4]
T0_nmb_casualties
```


```{r}
set.seed(4244)
bin_size <- 0.01 

T0_nmb_casualties <-summary(anova_result) [[1]][1,4]
T0_nmb_casualties

aov.H0nmb_casualties <- aov(accident_severity ~ weekend + light_conditions, data = dat)
residuals.H0nmb_casualties <- aov.H0nmb_casualties$residuals

T0_weekend <-summary(anova_result) [[1]][2,4]
T0_weekend
aov.H0weekend <- aov(accident_severity ~ number_of_casualties + light_conditions, data = dat)
residuals.H0weekend <- aov.H0weekend$residuals

T0_light <-summary(anova_result) [[1]][3,4]
T0_light
aov.H0light <- aov(accident_severity ~ number_of_casualties + weekend, data = dat)
residuals.H0light  <- aov.H0light$residuals


```



```{r}
B <- 1000
T_nmb_casualties <- T_weekend <- T_light <- numeric(B)
pb = progress::progress_bar$new(total = B, format = " Processing [:bar] :percent eta: :eta")

for(perm in 1:B){
  permutation <- sample(n)
  
  # Test number of casulaties
  sev.perm.H0nmb_casualties <- aov.H0nmb_casualties$fitted + residuals.H0nmb_casualties[permutation]
  T_nmb_casualties[perm] <- summary.aov(aov(sev.perm.H0nmb_casualties ~ number_of_casualties + weekend + light_conditions, data = dat))[[1]][1,4]
  
  # Test weekend
  sev.perm.H0weekend <- aov.H0weekend$fitted + residuals.H0weekend[permutation]
  T_weekend[perm] <- summary.aov(aov(sev.perm.H0weekend ~ number_of_casualties + weekend + light_conditions, data = dat))[[1]][2,4]
  
  # Test light
  sev.perm.H0light <- aov.H0light$fitted + residuals.H0light[permutation]
  T_light[perm] <- summary.aov(aov(sev.perm.H0light ~ number_of_casualties + weekend + light_conditions, data = dat))[[1]][3,4]
  pb$tick()
  
}

```
T_nmb_casualties

```{r}
print(sum(T_nmb_casualties >= T0_nmb_casualties)/B)
ggplot()+aes(T_nmb_casualties)+geom_histogram(binwidth = 0.4) + geom_vline(aes(xintercept=T0_nmb_casualties), color= "red")
ggplot()+aes(T_nmb_casualties)+stat_ecdf(geom = "step") + geom_vline(aes(xintercept=T0_nmb_casualties), color= "red")

```

```{r}
print(sum(T_weekend >= T0_weekend)/B)
ggplot()+aes(T_weekend)+geom_histogram(binwidth = 0.4) + geom_vline(aes(xintercept=T0_weekend), color= "red")
ggplot()+aes(T_weekend)+stat_ecdf(geom = "step") + geom_vline(aes(xintercept=T0_weekend), color= "red")
```

```{r}
sum(T_light >= T0_light)/B
ggplot()+aes(T_light)+geom_histogram(binwidth = 0.4) + geom_vline(aes(xintercept=T_light), color= "red")
ggplot()+aes(T_light)+stat_ecdf(geom = "step") + geom_vline(aes(xintercept=T_light), color= "red")
```

